name: flutter_peluqueriapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  http: ^1.6.0
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# -----------------------------------------------------------
# Configuración del proyecto Flutter (Material Design y Assets)
# -----------------------------------------------------------
flutter:
  uses-material-design: true
  # Asegúrate de descomentar y listar tu carpeta de assets si la usas
  # assets:
  #   - assets/images/ 

# -----------------------------------------------------------
# Configuración de flutter_native_splash (¡Asegúrate de la indentación!)
# -----------------------------------------------------------
flutter_native_splash:
  color: "#f4b95b" 
    # color_dark: "#000000" 

    # La imagen PNG a mostrar 
    # ¡IMPORTANTE! La ruta 'assets/images/splash.png' debe ser válida.
  image: assets/splash.png 
  android_12:
    # El fondo de la pantalla de inicio
    color: "#f4b95b" 
    # color_dark: "#000000" 

    # La imagen PNG a mostrar 
    # ¡IMPORTANTE! La ruta 'assets/images/splash.png' debe ser válida.
    image: assets/splash.png 
    # image_dark: assets/images/splash_dark.png

    # Opcional: Imagen de fondo (descomentar si se usa)
    # background_image: "assets/images/splash.png" 
    # background_image_dark: "assets/background_dark.png"
