name: flutter_peluqueriapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  http: ^1.6.0
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# -----------------------------------------------------------
# Configuración del proyecto Flutter (Material Design y Assets)
# -----------------------------------------------------------
flutter:
  uses-material-design: true
  assets:
    - assets/splash.png  # <-- aquí declaras tu asset

# -----------------------------------------------------------
# Configuración de flutter_native_splash
# -----------------------------------------------------------
flutter_native_splash:
  color: "#f4b95b"
  image: assets/splash.png
  android: true
  ios: true
  web: true
  android_12:
    color: "#f4b95b"
    image: assets/splash.png
